name: action1

on: pull_request

jobs:
  action1:
    runs-on: ubuntu-slim
    steps:
      - name: hello
        run: echo "hello"

      - name: action1
        uses: mikeharder/actions-test/action1@main
