name: action1

on: pull_request

jobs:
  action1:
    runs-on: ubuntu-slim
    steps:
      - name: hello
        run: echo "hello2"

      - name: action1
        uses: mikeharder/test-actions/action1@main

      - name: action2
        uses: mikeharder/test-actions/action2@main

      - name: action3
        uses: mikeharder/test-actions/action3@main

      - name: action4
        uses: mikeharder/test-actions/action4@main
